# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "review"
client_id = "eb693420099f56112efa8804d6649337"
application_url = "https://tradition-lightweight-permanent-sticky.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tradition-lightweight-permanent-sticky.trycloudflare.com/auth/callback",
  "https://tradition-lightweight-permanent-sticky.trycloudflare.com/auth/shopify/callback",
  "https://tradition-lightweight-permanent-sticky.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "staging-master-store.myshopify.com"
